# -*- coding: utf-8 -*-
"""SeoulBikes_StepByStep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKxGDHdgNjuGTG2h-GQl4AW6NEajo_dQ

# Seoul Bikes ETL
### Evan André Santana Pacheco A01769493
### TC3009C.601

Predictive Modeling of Urban Bike-Sharing Demand in Seoul
Seoul Bike Sharing Demand (UCI Machine Learning Repository)
Authors
https://archive.ics.uci.edu/dataset/560/seoul+bike+sharing+demand

Licence
Creative Commons Attribution 4.0 International (CC BY 4.0)

References

Series.dt.dayofweek
https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.dayofweek.html#pandas.Series.dt.dayofweek

Zip function
https://www.w3schools.com/python/trypython.asp?filename=demo_ref_zip

Libraries
"""

import pandas as pd
import numpy as np

"""#ETL

Load data
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive

drive.mount("/content/gdrive")

# %cd "/content/gdrive/MyDrive/IAconcentrada/seoul"
!ls

df = pd.read_csv('SeoulBikeData.csv', encoding='latin1')

"""Check correct extraction, general info and empty values"""

print(df.head())
print("\nDataset info:")
print(df.info(), "\n")
print("Null values\n", pd.isnull(df).sum(),"\n")

"""Transform Holiday.
Check first what values are present.
Based in that we can transform Holiday to binary either there is or doesnt.
Check if it was succesfull.
"""

diff_text = df['Holiday'].unique()
print(diff_text)

def changehol(text):
    if text == 'Holiday':
        return 1
    elif text == 'No Holiday':
        return 0

df['Holiday'] = df['Holiday'].apply(changehol)

df.head()['Holiday']

#Must be holiday
print(df.loc[df['Holiday'] == 1].head()['Holiday'])
#Must be no holiday
print(df.loc[df['Holiday'] == 0].head()['Holiday'])

"""Transform Seasons.
Check first what values are present.
Based in that we can transform 4 seasons into a int values.
Check if it was succesfull.
"""

diff_text = df['Seasons'].unique()
print(diff_text)

def changesea(text):
    if text == 'Winter':
        return 1
    if text == 'Spring':
        return 2
    if text == 'Summer':
        return 3
    elif text == 'Autumn':
        return 4

df['Seasons'] = df['Seasons'].apply(changesea)

# Check for Winter
print(df.loc[df['Seasons'] == 1].head()['Seasons'])
# Check for Spring
print(df.loc[df['Seasons'] == 2].head()['Seasons'])
# Check for Summer
print(df.loc[df['Seasons'] == 3].head()['Seasons'])
# Check for Autumn
print(df.loc[df['Seasons'] == 4].head()['Seasons'])

"""Transform Functioning Day.
Check first what values are present.
Based in that we can transform into binary Yes or Not.
Check if it was succesfull.
"""

diff_text = df['Functioning Day'].unique()
print(diff_text)

def changefun(text):
    if text == 'Yes':
        return 1
    elif text == 'No':
        return 0

df['Functioning Day'] = df['Functioning Day'].apply(changefun)

# Check for functioning days
print(df.loc[df['Functioning Day'] == 1].head()['Functioning Day'])
# Check for non functioning days
print(df.loc[df['Functioning Day'] == 0].head()['Functioning Day'])

"""Translate Visibility. First checking what are the max and min values due to missunderstand with units or concept of variable.
Based in that, we can translate as in 2000 100% of visibility or 1 and 0 as none. Check if translation was correct.
"""

print(df['Visibility (10m)'].max())
print(df['Visibility (10m)'].min())

df['Visibility (10m)'] = df['Visibility (10m)'].astype(float) / 2000.0

print(df.head()['Visibility (10m)'])
print("Min visibility:", df['Visibility (10m)'].min())

"""Confirmation of non functioning days. As expected on non functioning days there is no rented bikes. Everything else is normal."""

print(df.loc[df['Functioning Day'] == 0].head())

print("Non Functioning hours: ", (df['Functioning Day'] == 0).sum())
print("0 Rented bikes instances: ", (df['Rented Bike Count'] == 0).sum())

"""Perform imputation via interpolation of data in Rented Bike Count for any non functioning day. For any non functioning instance/hour we will find the exact hour of last day (idx - 24), exact hour of next day (idx + 24) while skipping consecutive non functioning days.
Its a fact that:
First 24 instances are functioning
The non functioning instances are 295/8760 - 3%
Only non functioning days presented 0 rented bikes

Its possible that:
There are consecutive days without functioning
There is no next day of a non functioning day (End of data)
There could be a small anomalie with interpolation

Therefore we can create and index, find the non functioning instance, finde the corresponding value before and after, calculate the interpolation and impute.

"""

# Imputation function

def imput(df):

    df_im = df.copy()
    index_fund = df_im[df_im['Functioning Day'] == 0].index

    for idx in index_fund:

        before = 24
        while (idx - before >= 0) and (df_im.loc[idx - before, 'Functioning Day'] == 0):
            before += 24

        next_step = 24
        while (idx + next_step < len(df_im)) and (df_im.loc[idx + next_step, 'Functioning Day'] == 0):
            next_step += 24

        b_val = df_im.loc[idx - before, 'Rented Bike Count'] if (idx - before >= 0) else np.nan
        n_val = df_im.loc[idx + next_step, 'Rented Bike Count'] if (idx + next_step < len(df_im)) else np.nan

        # Interpolation
        if pd.notna(b_val) and pd.notna(n_val):
            imputation = (b_val + n_val) / 2
        elif pd.notna(b_val):
            imputation = b_val
        elif pd.notna(n_val):
            imputation = n_val

        # Imputation
        df_im.loc[idx, 'Rented Bike Count'] = imputation

    return df_im

"""Impute and Check for correct imputation and type."""

df = imput(df)
print(df[df['Functioning Day'] == 0]['Rented Bike Count'].head())

print(df['Rented Bike Count'].info())

"""Transform Rented Bike count into Int type and round for all imputation with decimal values. Check for correct transformation. Check for complete imputation."""

df['Rented Bike Count'] = df['Rented Bike Count'].round().astype(int)
print("Tipo de dato:", df['Rented Bike Count'].dtype)
print(df[df['Functioning Day'] == 0]['Rented Bike Count'].head())
print((df['Rented Bike Count'] == 0 ).sum())

"""Create Weekend variable from Date. Date is already an object in format dd/mm/yyyy however is detected as an string and therefore is necessary to transform to values in same format. dt.dayofweek provides the order 0-6 Mondey through Sunday. Check for correct transformation."""

df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')
df['Weekend'] = np.where(df['Date'].dt.dayofweek >= 5, 1, 0)

print(df[df['Weekend'] == 1]['Weekend'].head())

"""Check the data general info, null values and type up to this point."""

print(df.head())
print("\nDataset info:")
print(df.info(), "\n")
print("Null values\n", pd.isnull(df).sum(),"\n")

"""Division of classes X_train, Y_train, X_test and Y_Test.
The test will represent aproximately 10% of data.

X_test, Y_test --> last 216 instances of each season.
X_train, Y_train --> remaining block of instances.
For dividing each chunk we will locate the position of season change and create arrange with the corresponding start and end of each season. We will append each chunk for each season with the located index values and train gets the chunk -216 and test the last 216 instances.
"""

df['instance_id'] = df.index

TEST_HOURS_PER_SEASON = 216

season_change = df['Seasons'] != df['Seasons'].shift()

block_starts = df.index[season_change].tolist()

block_ends = block_starts[1:] + [len(df)]

train_parts, test_parts, map_parts = [], [], []

for start, end in zip(block_starts, block_ends):
    block = df.iloc[start:end]
    block_train = block.iloc[:-TEST_HOURS_PER_SEASON]
    block_test  = block.iloc[-TEST_HOURS_PER_SEASON:]

    train_parts.append(block_train)
    test_parts.append(block_test)

    map_parts.append(block_train.assign(Subset='train', local_id=range(1, len(block_train) + 1)))
    map_parts.append(block_test.assign(Subset='test',  local_id=range(1, len(block_test) + 1)))

df_train = pd.concat(train_parts)
df_test  = pd.concat(test_parts)

map = pd.concat(map_parts).sort_values('instance_id')
map = map[['local_id', 'Date', 'Seasons', 'Subset', 'Functioning Day']].reset_index(drop=True)

drop_cols = ['Rented Bike Count', 'Date', 'Functioning Day', 'instance_id']
features = [col for col in df.columns if col not in drop_cols]

X_train, Y_train = df_train[features], df_train['Rented Bike Count']
X_test,  Y_test  = df_test[features],  df_test['Rented Bike Count']

"""The global index (instance_id) will provide the exact original order of instances therefore its possible to create a map.
Map will recieve all non machine learning model relevant information just for a tool to analyse data.
Recycling the information map will recieve the local_id of the set (season blocks) , the Date that could provide more information to the final analisis, Seasons which represented the 4 chunks or sets, the subset which indicate if is part of train or test and Functioning Day that could provide explanation for anomalies due to imputed interpolation values.

X blocks will have all features except the dropped columns.
Y blocks will only have Rented Bike count.

Verify the succesfull division of all blocks.


"""

print(f"Train rows: {len(df_train)} | Test rows: {len(df_test)}")

print("Map:\n", map.head())
print("X_train: \n",X_train.head())
print("Y_train: \n",Y_train.head())
print("X_test: \n",X_test.head())
print("Y_test: \n",Y_test.head())

"""We can exporta all data blocks."""

X_train.to_csv('X_train_seoul.csv', index=False)
Y_train.to_csv('Y_train_seoul.csv', index=False)
X_test.to_csv('X_test_seoul.csv', index=False)
Y_test.to_csv('Y_test_seoul.csv', index=False)
map.to_csv('map_seoulData.csv', index=False)

"""By this point we have a complete ETL on the data set.

We will start now with the EDA.
"""

